spring.application.name=SpringBootSecqurityEx

# ---------------------------
# JWT
# ---------------------------
app.jwt.secret=VGhpc0lzQVN1cGVyU2VjdXJlSldUVFNjcmV0S2V5Rm9yU3ByaW5nQm9vdDIwMjY=
app.jwt.expiration=86400000

# ---------------------------
# CORS
# ---------------------------
app.cors.allowed-origin-patterns=http://localhost:4200

# ---------------------------
# FIRST ADMIN
# ---------------------------
app.bootstrap-admin.username=admin
app.bootstrap-admin.email=admin@gmail.com
app.bootstrap-admin.password=admin123

# ---------------------------
# DATABASE
# ---------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/sbs
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------------------
# JPA / HIBERNATE
# ---------------------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ---------------------------
# SERVER
# ---------------------------
server.port=8080